import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { AuthProvider } from '@/contexts/auth'
import './global.css'
import AppearanceProvider from '@/contexts/appearance'


const satoshi = localFont({
  src: [
    { path: '../../public/fonts/Satoshi-Regular.woff2', weight: '400', },
    { path: '../../public/fonts/Satoshi-Medium.woff2', weight: '500', },
    { path: '../../public/fonts/Satoshi-Black.woff2', weight: '600', },
    { path: '../../public/fonts/Satoshi-Bold.woff2', weight: '700', },
  ],
  variable: '--font-satoshi',
  display: 'swap',
})

export const metadata: Metadata = {
  title: '/my-links',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      {/* Prefer Satoshi when available, fall back to Inter */}
      <body className={`${satoshi.className ?? ''}`}>
        <AuthProvider>
          <AppearanceProvider>
            {children}
          </AppearanceProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
